export type LayoutVariant =
  | "split-left"
  | "split-right"
  | "stacked"
  | "stacked-reverse"
  | "theater"
  | "columns"
  | "grid";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  layout: LayoutVariant;
  bodyClass: string;
  headerClass: string;
  headerTitleClass: string;
  layoutWrapperClass: string;
  effectsWrapperClass: string;
  mainWrapperClass: string;
  effectPanelClass: string;
  mainPanelClass: string;
  effectCardClass: string;
  effectCardActiveClass: string;
  effectCardTargetClass: string;
  buttonPrimaryClass: string;
  buttonSecondaryClass: string;
  buttonGhostClass: string;
  tagClass: string;
  mutedTextClass: string;
  headingTextClass: string;
  selectClass: string;
  inputClass: string;
  checkboxClass: string;
  dropzoneBaseClass: string;
  dropzoneActiveClass: string;
  dropzoneDisabledClass: string;
  audioPanelClass: string;
  audioPlayButtonClass: string;
  accentColor: string;
  waveColor: string;
  waveProgressColor: string;
  effectListClass?: string;
  effectCardWrapperClass?: string;
  effectCardBodyClass?: string;
  effectListEmptyClass?: string;
  mainInnerClass?: string;
  playerStackClass?: string;
  controlRowClass?: string;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "sunsetBloom",
    name: "Sunset Bloom",
    description: "Warm oranges and pinks with side-by-side layout and soft glass surfaces.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-rose-100 via-orange-100 to-amber-200 text-rose-900",
    headerClass: "bg-white/80 border-b border-amber-200 backdrop-blur",
    headerTitleClass: "text-rose-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white/90 border border-rose-200 shadow-lg shadow-rose-200/60 rounded-3xl backdrop-blur px-6 py-8",
    mainPanelClass: "bg-white/90 border border-amber-200 shadow-xl shadow-amber-200/60 rounded-3xl backdrop-blur px-8 py-10",
    effectCardClass: "bg-rose-50/90 border border-rose-200 rounded-2xl",
    effectCardActiveClass: "border-amber-400 shadow-[0_0_25px_rgba(245,158,11,0.35)]",
    effectCardTargetClass: "border-amber-300 bg-amber-100/60",
    buttonPrimaryClass: "bg-rose-500 hover:bg-rose-400 text-white rounded-full uppercase tracking-wide px-5 py-2",
    buttonSecondaryClass: "bg-amber-100 hover:bg-amber-200 text-amber-700 border border-amber-300 rounded-full uppercase tracking-wide px-5 py-2",
    buttonGhostClass: "bg-white hover:bg-rose-100 text-rose-600 border border-rose-200 rounded-full uppercase tracking-wide px-5 py-2",
    tagClass: "text-rose-600 bg-rose-100 border border-rose-200 rounded-full px-2",
    mutedTextClass: "text-rose-400",
    headingTextClass: "text-rose-700",
    selectClass: "bg-white border border-rose-200 text-rose-700 rounded-full focus:ring-1 focus:ring-rose-400 focus:border-rose-400",
    inputClass: "bg-white border border-rose-200 text-rose-700 rounded-full focus:ring-1 focus:ring-rose-400 focus:border-rose-400 placeholder-rose-300",
    checkboxClass: "text-rose-500 focus:ring-rose-300 border-rose-300 rounded-md",
    dropzoneBaseClass: "border-rose-300 border-dashed bg-rose-50 text-rose-600 hover:bg-rose-100 rounded-[3rem]",
    dropzoneActiveClass: "border-amber-400 bg-amber-100 scale-[1.02]",
    dropzoneDisabledClass: "opacity-50 cursor-not-allowed",
    audioPanelClass: "bg-white/90 border border-rose-200 shadow-lg rounded-3xl",
    audioPlayButtonClass: "bg-rose-500 hover:bg-rose-400 text-white rounded-full uppercase tracking-wide px-5 py-2",
    accentColor: "#f472b6",
    waveColor: "#fca5a5",
    waveProgressColor: "#fb7185",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-rose-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "blossomDesk",
    name: "Blossom Desk",
    description: "Minimal workspace with sunset bloom colors - warm rose and amber tones.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-stone-100 via-neutral-100 to-stone-100 text-stone-800",
    headerClass: "bg-gradient-to-r from-rose-50/80 via-white to-amber-50/80 border-b border-rose-200/60 backdrop-blur-sm",
    headerTitleClass: "text-rose-800 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-6 py-8",
    mainPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-8 py-10",
    effectCardClass: "bg-stone-50 border border-stone-200 rounded-none",
    effectCardActiveClass: "border-rose-400 shadow-[0_0_20px_rgba(244,114,182,0.15)]",
    effectCardTargetClass: "border-amber-400 bg-amber-50/60",
    buttonPrimaryClass: "bg-rose-600 hover:bg-rose-700 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    buttonSecondaryClass: "bg-white hover:bg-stone-50 text-stone-700 border border-stone-300 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow transition-shadow",
    buttonGhostClass: "bg-transparent border border-stone-300 text-stone-600 hover:bg-stone-50 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none hover:border-stone-400 transition-colors",
    tagClass: "text-stone-700 bg-stone-100 border border-stone-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-stone-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-stone-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-rose-400 focus:border-rose-400",
    inputClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-rose-400 focus:border-rose-400 placeholder-stone-400",
    checkboxClass: "text-rose-600 focus:ring-rose-400 border-stone-300 rounded-none",
    dropzoneBaseClass: "border-stone-300 border-dashed bg-white text-stone-600 hover:bg-stone-50 rounded-none uppercase tracking-[0.25em] px-8 py-10",
    dropzoneActiveClass: "border-rose-400 bg-rose-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-stone-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-rose-600 hover:bg-rose-700 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    accentColor: "#e11d48",
    waveColor: "#fecdd3",
    waveProgressColor: "#e11d48",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-rose-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "terraDesk",
    name: "Terra Desk",
    description: "Warm earthy workspace with terracotta and clay tones.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-stone-200 via-neutral-100 to-stone-100 text-stone-900",
    headerClass: "bg-gradient-to-r from-orange-50/60 via-white to-stone-50/80 border-b border-orange-200/50",
    headerTitleClass: "text-orange-900 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-6 py-8",
    mainPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-8 py-10",
    effectCardClass: "bg-stone-50 border border-stone-200 rounded-none",
    effectCardActiveClass: "border-orange-500 shadow-[0_0_20px_rgba(194,65,12,0.15)]",
    effectCardTargetClass: "border-orange-400 bg-orange-50",
    buttonPrimaryClass: "bg-orange-700 hover:bg-orange-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    buttonSecondaryClass: "bg-white hover:bg-stone-50 text-stone-700 border border-stone-300 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow transition-shadow",
    buttonGhostClass: "bg-transparent border border-stone-300 text-stone-600 hover:bg-stone-50 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none hover:border-stone-400 transition-colors",
    tagClass: "text-stone-700 bg-stone-100 border border-stone-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-stone-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-stone-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-orange-500 focus:border-orange-500",
    inputClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-orange-500 focus:border-orange-500 placeholder-stone-400",
    checkboxClass: "text-orange-700 focus:ring-orange-500 border-stone-300 rounded-none",
    dropzoneBaseClass: "border-stone-300 border-dashed bg-white text-stone-600 hover:bg-stone-50 rounded-none uppercase tracking-[0.25em] px-8 py-10",
    dropzoneActiveClass: "border-orange-400 bg-orange-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-stone-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-orange-700 hover:bg-orange-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    accentColor: "#c2410c",
    waveColor: "#fed7aa",
    waveProgressColor: "#c2410c",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-orange-600",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "honeyDesk",
    name: "Honey Desk",
    description: "Warm golden workspace with honey and amber accents.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-stone-200 via-amber-100 to-stone-100 text-stone-900",
    headerClass: "bg-gradient-to-r from-amber-50/60 via-white to-yellow-50/60 border-b border-amber-200/50",
    headerTitleClass: "text-amber-900 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-6 py-8",
    mainPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-8 py-10",
    effectCardClass: "bg-stone-50 border border-stone-200 rounded-none",
    effectCardActiveClass: "border-amber-500 shadow-[0_0_20px_rgba(217,119,6,0.15)]",
    effectCardTargetClass: "border-amber-400 bg-amber-50",
    buttonPrimaryClass: "bg-amber-600 hover:bg-amber-700 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    buttonSecondaryClass: "bg-white hover:bg-stone-50 text-stone-700 border border-stone-300 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow transition-shadow",
    buttonGhostClass: "bg-transparent border border-stone-300 text-stone-600 hover:bg-stone-50 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none hover:border-stone-400 transition-colors",
    tagClass: "text-stone-700 bg-stone-100 border border-stone-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-stone-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-stone-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-amber-500 focus:border-amber-500",
    inputClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-amber-500 focus:border-amber-500 placeholder-stone-400",
    checkboxClass: "text-amber-600 focus:ring-amber-500 border-stone-300 rounded-none",
    dropzoneBaseClass: "border-stone-300 border-dashed bg-white text-stone-600 hover:bg-stone-50 rounded-none uppercase tracking-[0.25em] px-8 py-10",
    dropzoneActiveClass: "border-amber-400 bg-amber-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-stone-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-amber-600 hover:bg-amber-700 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    accentColor: "#d97706",
    waveColor: "#fef3c7",
    waveProgressColor: "#d97706",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-amber-600",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "copperDesk",
    name: "Copper Desk",
    description: "Warm metallic workspace with rich copper and bronze tones.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-stone-200 via-orange-100 to-stone-100 text-stone-900",
    headerClass: "bg-gradient-to-r from-orange-100/60 via-white to-orange-50/60 border-b border-orange-300/50",
    headerTitleClass: "text-orange-900 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-6 py-8",
    mainPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-8 py-10",
    effectCardClass: "bg-stone-50 border border-stone-200 rounded-none",
    effectCardActiveClass: "border-orange-600 shadow-[0_0_20px_rgba(154,52,18,0.15)]",
    effectCardTargetClass: "border-orange-400 bg-orange-50",
    buttonPrimaryClass: "bg-orange-700 hover:bg-orange-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    buttonSecondaryClass: "bg-white hover:bg-stone-50 text-stone-700 border border-stone-300 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow transition-shadow",
    buttonGhostClass: "bg-transparent border border-stone-300 text-stone-600 hover:bg-stone-50 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none hover:border-stone-400 transition-colors",
    tagClass: "text-stone-700 bg-stone-100 border border-stone-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-stone-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-stone-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-orange-600 focus:border-orange-600",
    inputClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-orange-600 focus:border-orange-600 placeholder-stone-400",
    checkboxClass: "text-orange-700 focus:ring-orange-600 border-stone-300 rounded-none",
    dropzoneBaseClass: "border-stone-300 border-dashed bg-white text-stone-600 hover:bg-stone-50 rounded-none uppercase tracking-[0.25em] px-8 py-10",
    dropzoneActiveClass: "border-orange-400 bg-orange-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-stone-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-orange-700 hover:bg-orange-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    accentColor: "#9a3412",
    waveColor: "#ffedd5",
    waveProgressColor: "#9a3412",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-orange-700",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "mossDesk",
    name: "Moss Desk",
    description: "Warm earthy workspace with olive and moss green tones.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-stone-200 via-lime-100 to-stone-100 text-stone-900",
    headerClass: "bg-gradient-to-r from-lime-50/60 via-white to-green-50/60 border-b border-lime-200/50",
    headerTitleClass: "text-green-900 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-6 py-8",
    mainPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-8 py-10",
    effectCardClass: "bg-stone-50 border border-stone-200 rounded-none",
    effectCardActiveClass: "border-lime-600 shadow-[0_0_20px_rgba(77,124,15,0.15)]",
    effectCardTargetClass: "border-lime-400 bg-lime-50",
    buttonPrimaryClass: "bg-lime-700 hover:bg-lime-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    buttonSecondaryClass: "bg-white hover:bg-stone-50 text-stone-700 border border-stone-300 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow transition-shadow",
    buttonGhostClass: "bg-transparent border border-stone-300 text-stone-600 hover:bg-stone-50 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none hover:border-stone-400 transition-colors",
    tagClass: "text-stone-700 bg-stone-100 border border-stone-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-stone-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-stone-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-lime-600 focus:border-lime-600",
    inputClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-lime-600 focus:border-lime-600 placeholder-stone-400",
    checkboxClass: "text-lime-700 focus:ring-lime-600 border-stone-300 rounded-none",
    dropzoneBaseClass: "border-stone-300 border-dashed bg-white text-stone-600 hover:bg-stone-50 rounded-none uppercase tracking-[0.25em] px-8 py-10",
    dropzoneActiveClass: "border-lime-400 bg-lime-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-stone-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-lime-700 hover:bg-lime-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    accentColor: "#4d7c0f",
    waveColor: "#ecfccb",
    waveProgressColor: "#4d7c0f",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-lime-700",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "brickDesk",
    name: "Brick Desk",
    description: "Warm workspace with deep red and burgundy brick tones.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-stone-200 via-red-100 to-stone-100 text-stone-900",
    headerClass: "bg-gradient-to-r from-red-50/60 via-white to-rose-50/60 border-b border-red-200/50",
    headerTitleClass: "text-red-900 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-6 py-8",
    mainPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-8 py-10",
    effectCardClass: "bg-stone-50 border border-stone-200 rounded-none",
    effectCardActiveClass: "border-red-600 shadow-[0_0_20px_rgba(153,27,27,0.15)]",
    effectCardTargetClass: "border-red-400 bg-red-50",
    buttonPrimaryClass: "bg-red-700 hover:bg-red-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    buttonSecondaryClass: "bg-white hover:bg-stone-50 text-stone-700 border border-stone-300 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow transition-shadow",
    buttonGhostClass: "bg-transparent border border-stone-300 text-stone-600 hover:bg-stone-50 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none hover:border-stone-400 transition-colors",
    tagClass: "text-stone-700 bg-stone-100 border border-stone-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-stone-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-stone-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-red-600 focus:border-red-600",
    inputClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-red-600 focus:border-red-600 placeholder-stone-400",
    checkboxClass: "text-red-700 focus:ring-red-600 border-stone-300 rounded-none",
    dropzoneBaseClass: "border-stone-300 border-dashed bg-white text-stone-600 hover:bg-stone-50 rounded-none uppercase tracking-[0.25em] px-8 py-10",
    dropzoneActiveClass: "border-red-400 bg-red-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-stone-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-red-700 hover:bg-red-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    accentColor: "#991b1b",
    waveColor: "#fee2e2",
    waveProgressColor: "#991b1b",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-red-600",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "sandDesk",
    name: "Sand Desk",
    description: "Warm neutral workspace with sandy beige and tan tones.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-stone-200 via-neutral-100 to-stone-100 text-stone-900",
    headerClass: "bg-gradient-to-r from-stone-100/80 via-white to-stone-50/80 border-b border-stone-300/60",
    headerTitleClass: "text-stone-800 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-6 py-8",
    mainPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-8 py-10",
    effectCardClass: "bg-stone-50 border border-stone-200 rounded-none",
    effectCardActiveClass: "border-stone-600 shadow-[0_0_20px_rgba(68,64,60,0.15)]",
    effectCardTargetClass: "border-stone-400 bg-stone-100",
    buttonPrimaryClass: "bg-stone-700 hover:bg-stone-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    buttonSecondaryClass: "bg-white hover:bg-stone-50 text-stone-700 border border-stone-300 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow transition-shadow",
    buttonGhostClass: "bg-transparent border border-stone-300 text-stone-600 hover:bg-stone-50 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none hover:border-stone-400 transition-colors",
    tagClass: "text-stone-700 bg-stone-100 border border-stone-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-stone-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-stone-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-stone-600 focus:border-stone-600",
    inputClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-stone-600 focus:border-stone-600 placeholder-stone-400",
    checkboxClass: "text-stone-700 focus:ring-stone-600 border-stone-300 rounded-none",
    dropzoneBaseClass: "border-stone-300 border-dashed bg-white text-stone-600 hover:bg-stone-50 rounded-none uppercase tracking-[0.25em] px-8 py-10",
    dropzoneActiveClass: "border-stone-400 bg-stone-100 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-stone-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-stone-700 hover:bg-stone-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    accentColor: "#78716c",
    waveColor: "#e7e5e4",
    waveProgressColor: "#78716c",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-stone-500",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "clayDesk",
    name: "Clay Desk",
    description: "Warm earthy workspace with brown and clay terracotta tones.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-stone-200 via-amber-100 to-orange-100 text-stone-900",
    headerClass: "bg-gradient-to-r from-amber-100/60 via-white to-orange-50/60 border-b border-amber-300/50",
    headerTitleClass: "text-amber-950 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-6 py-8",
    mainPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-8 py-10",
    effectCardClass: "bg-stone-50 border border-stone-200 rounded-none",
    effectCardActiveClass: "border-amber-600 shadow-[0_0_20px_rgba(146,64,14,0.15)]",
    effectCardTargetClass: "border-amber-400 bg-amber-50",
    buttonPrimaryClass: "bg-amber-700 hover:bg-amber-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    buttonSecondaryClass: "bg-white hover:bg-stone-50 text-stone-700 border border-stone-300 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow transition-shadow",
    buttonGhostClass: "bg-transparent border border-stone-300 text-stone-600 hover:bg-stone-50 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none hover:border-stone-400 transition-colors",
    tagClass: "text-stone-700 bg-stone-100 border border-stone-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-stone-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-stone-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-amber-600 focus:border-amber-600",
    inputClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-amber-600 focus:border-amber-600 placeholder-stone-400",
    checkboxClass: "text-amber-700 focus:ring-amber-600 border-stone-300 rounded-none",
    dropzoneBaseClass: "border-stone-300 border-dashed bg-white text-stone-600 hover:bg-stone-50 rounded-none uppercase tracking-[0.25em] px-8 py-10",
    dropzoneActiveClass: "border-amber-400 bg-amber-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-stone-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-amber-700 hover:bg-amber-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    accentColor: "#92400e",
    waveColor: "#fef3c7",
    waveProgressColor: "#92400e",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-amber-700",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "amberDesk",
    name: "Amber Desk",
    description: "Warm glowing workspace with rich amber and orange tones.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-stone-200 via-yellow-100 to-amber-100 text-stone-900",
    headerClass: "bg-gradient-to-r from-yellow-50/60 via-white to-amber-50/60 border-b border-amber-200/50",
    headerTitleClass: "text-amber-900 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-6 py-8",
    mainPanelClass: "bg-white border border-stone-200 rounded-none shadow-[0_20px_40px_rgba(0,0,0,0.06)] px-8 py-10",
    effectCardClass: "bg-stone-50 border border-stone-200 rounded-none",
    effectCardActiveClass: "border-amber-600 shadow-[0_0_20px_rgba(180,83,9,0.15)]",
    effectCardTargetClass: "border-amber-400 bg-amber-50",
    buttonPrimaryClass: "bg-amber-700 hover:bg-amber-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    buttonSecondaryClass: "bg-white hover:bg-stone-50 text-stone-700 border border-stone-300 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow transition-shadow",
    buttonGhostClass: "bg-transparent border border-stone-300 text-stone-600 hover:bg-stone-50 uppercase tracking-[0.15em] px-6 py-2.5 rounded-none hover:border-stone-400 transition-colors",
    tagClass: "text-stone-700 bg-stone-100 border border-stone-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-stone-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-stone-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-amber-600 focus:border-amber-600",
    inputClass: "bg-white border border-stone-300 text-stone-700 rounded-none uppercase tracking-[0.15em] focus:ring-1 focus:ring-amber-600 focus:border-amber-600 placeholder-stone-400",
    checkboxClass: "text-amber-700 focus:ring-amber-600 border-stone-300 rounded-none",
    dropzoneBaseClass: "border-stone-300 border-dashed bg-white text-stone-600 hover:bg-stone-50 rounded-none uppercase tracking-[0.25em] px-8 py-10",
    dropzoneActiveClass: "border-amber-400 bg-amber-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-stone-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-amber-700 hover:bg-amber-800 text-white uppercase tracking-[0.15em] px-6 py-2.5 rounded-none shadow-sm hover:shadow-md transition-shadow",
    accentColor: "#b45309",
    waveColor: "#fef3c7",
    waveProgressColor: "#b45309",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-amber-600",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "monoDesk",
    name: "Mono Desk",
    description: "Ultra-minimal white workstation with slim outlined controls and left-aligned cards.",
    layout: "split-left",
    bodyClass: "bg-[#f5f7fa] text-slate-900",
    headerClass: "bg-white border-b border-slate-200",
    headerTitleClass: "text-slate-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-slate-200 rounded-none shadow-[0_25px_50px_rgba(15,23,42,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-slate-200 rounded-none shadow-[0_30px_60px_rgba(15,23,42,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-slate-200 rounded-none",
    effectCardActiveClass: "border-slate-900 shadow-[0_0_25px_rgba(15,23,42,0.2)]",
    effectCardTargetClass: "border-blue-400 bg-blue-100/60",
    buttonPrimaryClass: "bg-slate-900 hover:bg-slate-700 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-slate-100 text-slate-700 border border-slate-300 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-slate-300 text-slate-600 hover:bg-slate-100 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-slate-600 bg-slate-100 border border-slate-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-slate-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-slate-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-slate-300 text-slate-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-slate-400 focus:border-slate-400",
    inputClass: "bg-white border border-slate-300 text-slate-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-slate-400 focus:border-slate-400 placeholder-slate-400",
    checkboxClass: "text-slate-700 focus:ring-slate-400 border-slate-300 rounded-none",
    dropzoneBaseClass: "border-slate-300 border-dashed bg-white text-slate-600 hover:bg-slate-100 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-blue-300 bg-blue-100/60 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-slate-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-slate-900 hover:bg-slate-700 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#0f172a",
    waveColor: "#cbd5f5",
    waveProgressColor: "#0f172a",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-slate-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  }
];
