export type LayoutVariant =
  | "split-left"
  | "split-right"
  | "stacked"
  | "stacked-reverse"
  | "theater"
  | "columns"
  | "grid";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  layout: LayoutVariant;
  bodyClass: string;
  headerClass: string;
  headerTitleClass: string;
  layoutWrapperClass: string;
  effectsWrapperClass: string;
  mainWrapperClass: string;
  effectPanelClass: string;
  mainPanelClass: string;
  effectCardClass: string;
  effectCardActiveClass: string;
  effectCardTargetClass: string;
  buttonPrimaryClass: string;
  buttonSecondaryClass: string;
  buttonGhostClass: string;
  tagClass: string;
  mutedTextClass: string;
  headingTextClass: string;
  selectClass: string;
  inputClass: string;
  checkboxClass: string;
  dropzoneBaseClass: string;
  dropzoneActiveClass: string;
  dropzoneDisabledClass: string;
  audioPanelClass: string;
  audioPlayButtonClass: string;
  accentColor: string;
  waveColor: string;
  waveProgressColor: string;
  effectListClass?: string;
  effectCardWrapperClass?: string;
  effectCardBodyClass?: string;
  effectListEmptyClass?: string;
  mainInnerClass?: string;
  playerStackClass?: string;
  controlRowClass?: string;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "sunsetBloom",
    name: "Sunset Bloom",
    description: "Warm oranges and pinks with side-by-side layout and soft glass surfaces.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-br from-rose-100 via-orange-100 to-amber-200 text-rose-900",
    headerClass: "bg-white/80 border-b border-amber-200 backdrop-blur",
    headerTitleClass: "text-rose-700",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-8",
    effectsWrapperClass: "xl:w-[22rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white/90 border border-rose-200 shadow-lg shadow-rose-200/60 rounded-3xl backdrop-blur px-6 py-8",
    mainPanelClass: "bg-white/90 border border-amber-200 shadow-xl shadow-amber-200/60 rounded-3xl backdrop-blur",
    effectCardClass: "bg-rose-50/90 border border-rose-200 rounded-2xl",
    effectCardActiveClass: "border-amber-400 shadow-[0_0_25px_rgba(245,158,11,0.35)]",
    effectCardTargetClass: "border-amber-300 bg-amber-100/60",
    buttonPrimaryClass: "bg-rose-500 hover:bg-rose-400 text-white rounded-full uppercase tracking-wide px-5 py-2",
    buttonSecondaryClass: "bg-amber-100 hover:bg-amber-200 text-amber-700 border border-amber-300 rounded-full uppercase tracking-wide px-5 py-2",
    buttonGhostClass: "bg-white hover:bg-rose-100 text-rose-600 border border-rose-200 rounded-full uppercase tracking-wide px-5 py-2",
    tagClass: "text-rose-600 bg-rose-100 border border-rose-200 rounded-full px-2",
    mutedTextClass: "text-rose-400",
    headingTextClass: "text-rose-700",
    selectClass: "bg-white border border-rose-200 text-rose-700 rounded-full focus:ring-1 focus:ring-rose-400 focus:border-rose-400",
    inputClass: "bg-white border border-rose-200 text-rose-700 rounded-full focus:ring-1 focus:ring-rose-400 focus:border-rose-400 placeholder-rose-300",
    checkboxClass: "text-rose-500 focus:ring-rose-300 border-rose-300 rounded-md",
    dropzoneBaseClass: "border-rose-300 border-dashed bg-rose-50 text-rose-600 hover:bg-rose-100 rounded-[3rem]",
    dropzoneActiveClass: "border-amber-400 bg-amber-100 scale-[1.02]",
    dropzoneDisabledClass: "opacity-50 cursor-not-allowed",
    audioPanelClass: "bg-white/90 border border-rose-200 shadow-lg rounded-3xl",
    audioPlayButtonClass: "bg-rose-500 hover:bg-rose-400 text-white rounded-full uppercase tracking-wide px-5 py-2",
    accentColor: "#f472b6",
    waveColor: "#fca5a5",
    waveProgressColor: "#fb7185",
    effectListClass: "space-y-4",
    effectListEmptyClass: "text-center py-8 text-sm text-rose-400 uppercase tracking-wide",
    mainInnerClass: "space-y-6",
    playerStackClass: "space-y-4",
    controlRowClass: "flex flex-col gap-2 sm:flex-row",
  },
  {
    id: "oceanDesk",
    name: "Ocean Desk",
    description: "Minimal blue workspace with clean lines and calm ocean tones.",
    layout: "split-left",
    bodyClass: "bg-[#f0f9ff] text-slate-900",
    headerClass: "bg-white border-b border-blue-200",
    headerTitleClass: "text-blue-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-blue-200 rounded-none shadow-[0_25px_50px_rgba(59,130,246,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-blue-200 rounded-none shadow-[0_30px_60px_rgba(59,130,246,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-blue-200 rounded-none",
    effectCardActiveClass: "border-blue-600 shadow-[0_0_25px_rgba(37,99,235,0.2)]",
    effectCardTargetClass: "border-cyan-400 bg-cyan-50",
    buttonPrimaryClass: "bg-blue-600 hover:bg-blue-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-blue-50 text-blue-700 border border-blue-300 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-blue-300 text-blue-600 hover:bg-blue-50 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-blue-600 bg-blue-50 border border-blue-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-blue-400 uppercase tracking-[0.2em]",
    headingTextClass: "text-blue-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-blue-300 text-blue-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-blue-400 focus:border-blue-400",
    inputClass: "bg-white border border-blue-300 text-blue-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-blue-400 focus:border-blue-400 placeholder-blue-400",
    checkboxClass: "text-blue-700 focus:ring-blue-400 border-blue-300 rounded-none",
    dropzoneBaseClass: "border-blue-300 border-dashed bg-white text-blue-600 hover:bg-blue-50 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-cyan-300 bg-cyan-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-blue-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-blue-600 hover:bg-blue-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#2563eb",
    waveColor: "#bfdbfe",
    waveProgressColor: "#2563eb",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-blue-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "forestDesk",
    name: "Forest Desk",
    description: "Minimal green workspace with natural tones and clean structure.",
    layout: "split-left",
    bodyClass: "bg-[#f0fdf4] text-slate-900",
    headerClass: "bg-white border-b border-emerald-200",
    headerTitleClass: "text-emerald-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-emerald-200 rounded-none shadow-[0_25px_50px_rgba(16,185,129,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-emerald-200 rounded-none shadow-[0_30px_60px_rgba(16,185,129,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-emerald-200 rounded-none",
    effectCardActiveClass: "border-emerald-600 shadow-[0_0_25px_rgba(5,150,105,0.2)]",
    effectCardTargetClass: "border-green-400 bg-green-50",
    buttonPrimaryClass: "bg-emerald-600 hover:bg-emerald-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-emerald-50 text-emerald-700 border border-emerald-300 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-emerald-300 text-emerald-600 hover:bg-emerald-50 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-emerald-600 bg-emerald-50 border border-emerald-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-emerald-400 uppercase tracking-[0.2em]",
    headingTextClass: "text-emerald-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-emerald-300 text-emerald-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-emerald-400 focus:border-emerald-400",
    inputClass: "bg-white border border-emerald-300 text-emerald-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-emerald-400 focus:border-emerald-400 placeholder-emerald-400",
    checkboxClass: "text-emerald-700 focus:ring-emerald-400 border-emerald-300 rounded-none",
    dropzoneBaseClass: "border-emerald-300 border-dashed bg-white text-emerald-600 hover:bg-emerald-50 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-green-300 bg-green-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-emerald-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-emerald-600 hover:bg-emerald-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#059669",
    waveColor: "#a7f3d0",
    waveProgressColor: "#059669",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-emerald-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "sunsetDesk",
    name: "Sunset Desk",
    description: "Minimal warm workspace with vibrant sunset orange accents.",
    layout: "split-left",
    bodyClass: "bg-[#fff7ed] text-slate-900",
    headerClass: "bg-white border-b border-orange-200",
    headerTitleClass: "text-orange-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-orange-200 rounded-none shadow-[0_25px_50px_rgba(249,115,22,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-orange-200 rounded-none shadow-[0_30px_60px_rgba(249,115,22,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-orange-200 rounded-none",
    effectCardActiveClass: "border-orange-600 shadow-[0_0_25px_rgba(234,88,12,0.2)]",
    effectCardTargetClass: "border-amber-400 bg-amber-50",
    buttonPrimaryClass: "bg-orange-600 hover:bg-orange-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-orange-50 text-orange-700 border border-orange-300 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-orange-300 text-orange-600 hover:bg-orange-50 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-orange-600 bg-orange-50 border border-orange-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-orange-400 uppercase tracking-[0.2em]",
    headingTextClass: "text-orange-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-orange-300 text-orange-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-orange-400 focus:border-orange-400",
    inputClass: "bg-white border border-orange-300 text-orange-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-orange-400 focus:border-orange-400 placeholder-orange-400",
    checkboxClass: "text-orange-700 focus:ring-orange-400 border-orange-300 rounded-none",
    dropzoneBaseClass: "border-orange-300 border-dashed bg-white text-orange-600 hover:bg-orange-50 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-amber-300 bg-amber-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-orange-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-orange-600 hover:bg-orange-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#ea580c",
    waveColor: "#fed7aa",
    waveProgressColor: "#ea580c",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-orange-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "lavenderDesk",
    name: "Lavender Desk",
    description: "Minimal purple workspace with soft lavender tones and clean edges.",
    layout: "split-left",
    bodyClass: "bg-[#faf5ff] text-slate-900",
    headerClass: "bg-white border-b border-purple-200",
    headerTitleClass: "text-purple-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-purple-200 rounded-none shadow-[0_25px_50px_rgba(147,51,234,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-purple-200 rounded-none shadow-[0_30px_60px_rgba(147,51,234,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-purple-200 rounded-none",
    effectCardActiveClass: "border-purple-600 shadow-[0_0_25px_rgba(126,34,206,0.2)]",
    effectCardTargetClass: "border-violet-400 bg-violet-50",
    buttonPrimaryClass: "bg-purple-600 hover:bg-purple-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-purple-50 text-purple-700 border border-purple-300 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-purple-300 text-purple-600 hover:bg-purple-50 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-purple-600 bg-purple-50 border border-purple-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-purple-400 uppercase tracking-[0.2em]",
    headingTextClass: "text-purple-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-purple-300 text-purple-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-purple-400 focus:border-purple-400",
    inputClass: "bg-white border border-purple-300 text-purple-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-purple-400 focus:border-purple-400 placeholder-purple-400",
    checkboxClass: "text-purple-700 focus:ring-purple-400 border-purple-300 rounded-none",
    dropzoneBaseClass: "border-purple-300 border-dashed bg-white text-purple-600 hover:bg-purple-50 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-violet-300 bg-violet-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-purple-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-purple-600 hover:bg-purple-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#9333ea",
    waveColor: "#e9d5ff",
    waveProgressColor: "#9333ea",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-purple-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "roseDesk",
    name: "Rose Desk",
    description: "Minimal pink workspace with delicate rose accents and sharp borders.",
    layout: "split-left",
    bodyClass: "bg-[#fdf2f8] text-slate-900",
    headerClass: "bg-white border-b border-pink-200",
    headerTitleClass: "text-pink-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-pink-200 rounded-none shadow-[0_25px_50px_rgba(236,72,153,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-pink-200 rounded-none shadow-[0_30px_60px_rgba(236,72,153,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-pink-200 rounded-none",
    effectCardActiveClass: "border-pink-600 shadow-[0_0_25px_rgba(219,39,119,0.2)]",
    effectCardTargetClass: "border-rose-400 bg-rose-50",
    buttonPrimaryClass: "bg-pink-600 hover:bg-pink-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-pink-50 text-pink-700 border border-pink-300 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-pink-300 text-pink-600 hover:bg-pink-50 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-pink-600 bg-pink-50 border border-pink-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-pink-400 uppercase tracking-[0.2em]",
    headingTextClass: "text-pink-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-pink-300 text-pink-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-pink-400 focus:border-pink-400",
    inputClass: "bg-white border border-pink-300 text-pink-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-pink-400 focus:border-pink-400 placeholder-pink-400",
    checkboxClass: "text-pink-700 focus:ring-pink-400 border-pink-300 rounded-none",
    dropzoneBaseClass: "border-pink-300 border-dashed bg-white text-pink-600 hover:bg-pink-50 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-rose-300 bg-rose-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-pink-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-pink-600 hover:bg-pink-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#db2777",
    waveColor: "#fbcfe8",
    waveProgressColor: "#db2777",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-pink-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "charcoalDesk",
    name: "Charcoal Desk",
    description: "Minimal dark workspace with charcoal tones and precise outlines.",
    layout: "split-left",
    bodyClass: "bg-[#fafafa] text-slate-900",
    headerClass: "bg-white border-b border-gray-300",
    headerTitleClass: "text-gray-800 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-gray-300 rounded-none shadow-[0_25px_50px_rgba(75,85,99,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-gray-300 rounded-none shadow-[0_30px_60px_rgba(75,85,99,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-gray-300 rounded-none",
    effectCardActiveClass: "border-gray-700 shadow-[0_0_25px_rgba(55,65,81,0.2)]",
    effectCardTargetClass: "border-gray-500 bg-gray-100",
    buttonPrimaryClass: "bg-gray-800 hover:bg-gray-700 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-gray-100 text-gray-800 border border-gray-400 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-gray-400 text-gray-700 hover:bg-gray-100 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-gray-700 bg-gray-100 border border-gray-300 uppercase tracking-wide px-2",
    mutedTextClass: "text-gray-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-gray-800 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-gray-400 text-gray-800 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-gray-500 focus:border-gray-500",
    inputClass: "bg-white border border-gray-400 text-gray-800 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-gray-500 focus:border-gray-500 placeholder-gray-500",
    checkboxClass: "text-gray-800 focus:ring-gray-500 border-gray-400 rounded-none",
    dropzoneBaseClass: "border-gray-400 border-dashed bg-white text-gray-700 hover:bg-gray-100 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-gray-500 bg-gray-100 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-gray-300 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-gray-800 hover:bg-gray-700 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#1f2937",
    waveColor: "#d1d5db",
    waveProgressColor: "#1f2937",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-gray-500",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "creamDesk",
    name: "Cream Desk",
    description: "Minimal warm workspace with cream tones and soft neutrals.",
    layout: "split-left",
    bodyClass: "bg-[#fefce8] text-slate-900",
    headerClass: "bg-white border-b border-yellow-200",
    headerTitleClass: "text-yellow-800 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-yellow-200 rounded-none shadow-[0_25px_50px_rgba(202,138,4,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-yellow-200 rounded-none shadow-[0_30px_60px_rgba(202,138,4,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-yellow-200 rounded-none",
    effectCardActiveClass: "border-yellow-600 shadow-[0_0_25px_rgba(161,98,7,0.2)]",
    effectCardTargetClass: "border-amber-400 bg-amber-50",
    buttonPrimaryClass: "bg-yellow-600 hover:bg-yellow-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-yellow-50 text-yellow-800 border border-yellow-300 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-yellow-300 text-yellow-700 hover:bg-yellow-50 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-yellow-700 bg-yellow-50 border border-yellow-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-yellow-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-yellow-800 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-yellow-300 text-yellow-800 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-yellow-400 focus:border-yellow-400",
    inputClass: "bg-white border border-yellow-300 text-yellow-800 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-yellow-400 focus:border-yellow-400 placeholder-yellow-500",
    checkboxClass: "text-yellow-700 focus:ring-yellow-400 border-yellow-300 rounded-none",
    dropzoneBaseClass: "border-yellow-300 border-dashed bg-white text-yellow-700 hover:bg-yellow-50 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-amber-300 bg-amber-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-yellow-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-yellow-600 hover:bg-yellow-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#ca8a04",
    waveColor: "#fef3c7",
    waveProgressColor: "#ca8a04",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-yellow-500",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "mintDesk",
    name: "Mint Desk",
    description: "Minimal fresh workspace with cool mint tones and clean structure.",
    layout: "split-left",
    bodyClass: "bg-[#f0fdfa] text-slate-900",
    headerClass: "bg-white border-b border-teal-200",
    headerTitleClass: "text-teal-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-teal-200 rounded-none shadow-[0_25px_50px_rgba(20,184,166,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-teal-200 rounded-none shadow-[0_30px_60px_rgba(20,184,166,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-teal-200 rounded-none",
    effectCardActiveClass: "border-teal-600 shadow-[0_0_25px_rgba(13,148,136,0.2)]",
    effectCardTargetClass: "border-cyan-400 bg-cyan-50",
    buttonPrimaryClass: "bg-teal-600 hover:bg-teal-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-teal-50 text-teal-700 border border-teal-300 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-teal-300 text-teal-600 hover:bg-teal-50 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-teal-600 bg-teal-50 border border-teal-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-teal-400 uppercase tracking-[0.2em]",
    headingTextClass: "text-teal-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-teal-300 text-teal-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-teal-400 focus:border-teal-400",
    inputClass: "bg-white border border-teal-300 text-teal-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-teal-400 focus:border-teal-400 placeholder-teal-400",
    checkboxClass: "text-teal-700 focus:ring-teal-400 border-teal-300 rounded-none",
    dropzoneBaseClass: "border-teal-300 border-dashed bg-white text-teal-600 hover:bg-teal-50 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-cyan-300 bg-cyan-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-teal-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-teal-600 hover:bg-teal-500 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#0d9488",
    waveColor: "#ccfbf1",
    waveProgressColor: "#0d9488",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-teal-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "slateDesk",
    name: "Slate Desk",
    description: "Minimal cool workspace with slate gray tones and minimal aesthetic.",
    layout: "split-left",
    bodyClass: "bg-[#f8fafc] text-slate-900",
    headerClass: "bg-white border-b border-slate-300",
    headerTitleClass: "text-slate-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-slate-300 rounded-none shadow-[0_25px_50px_rgba(71,85,105,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-slate-300 rounded-none shadow-[0_30px_60px_rgba(71,85,105,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-slate-300 rounded-none",
    effectCardActiveClass: "border-slate-700 shadow-[0_0_25px_rgba(51,65,85,0.2)]",
    effectCardTargetClass: "border-indigo-400 bg-indigo-50",
    buttonPrimaryClass: "bg-slate-700 hover:bg-slate-600 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-slate-100 text-slate-700 border border-slate-400 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-slate-400 text-slate-600 hover:bg-slate-100 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-slate-600 bg-slate-100 border border-slate-300 uppercase tracking-wide px-2",
    mutedTextClass: "text-slate-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-slate-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-slate-400 text-slate-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-slate-500 focus:border-slate-500",
    inputClass: "bg-white border border-slate-400 text-slate-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-slate-500 focus:border-slate-500 placeholder-slate-500",
    checkboxClass: "text-slate-700 focus:ring-slate-500 border-slate-400 rounded-none",
    dropzoneBaseClass: "border-slate-400 border-dashed bg-white text-slate-600 hover:bg-slate-100 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-indigo-300 bg-indigo-50 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-slate-300 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-slate-700 hover:bg-slate-600 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#334155",
    waveColor: "#cbd5e1",
    waveProgressColor: "#334155",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-slate-500",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "monoDesk",
    name: "Mono Desk",
    description: "Ultra-minimal white workstation with slim outlined controls and left-aligned cards.",
    layout: "split-left",
    bodyClass: "bg-[#f5f7fa] text-slate-900",
    headerClass: "bg-white border-b border-slate-200",
    headerTitleClass: "text-slate-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-slate-200 rounded-none shadow-[0_25px_50px_rgba(15,23,42,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-slate-200 rounded-none shadow-[0_30px_60px_rgba(15,23,42,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-slate-200 rounded-none",
    effectCardActiveClass: "border-slate-900 shadow-[0_0_25px_rgba(15,23,42,0.2)]",
    effectCardTargetClass: "border-blue-400 bg-blue-100/60",
    buttonPrimaryClass: "bg-slate-900 hover:bg-slate-700 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-slate-100 text-slate-700 border border-slate-300 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-slate-300 text-slate-600 hover:bg-slate-100 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-slate-600 bg-slate-100 border border-slate-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-slate-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-slate-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-slate-300 text-slate-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-slate-400 focus:border-slate-400",
    inputClass: "bg-white border border-slate-300 text-slate-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-slate-400 focus:border-slate-400 placeholder-slate-400",
    checkboxClass: "text-slate-700 focus:ring-slate-400 border-slate-300 rounded-none",
    dropzoneBaseClass: "border-slate-300 border-dashed bg-white text-slate-600 hover:bg-slate-100 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-blue-300 bg-blue-100/60 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-slate-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-slate-900 hover:bg-slate-700 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#0f172a",
    waveColor: "#cbd5f5",
    waveProgressColor: "#0f172a",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-slate-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  }
];
