export type LayoutVariant =
  | "split-left"
  | "split-right"
  | "stacked"
  | "stacked-reverse"
  | "theater"
  | "columns"
  | "grid";

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  layout: LayoutVariant;
  bodyClass: string;
  headerClass: string;
  headerTitleClass: string;
  layoutWrapperClass: string;
  effectsWrapperClass: string;
  mainWrapperClass: string;
  effectPanelClass: string;
  mainPanelClass: string;
  effectCardClass: string;
  effectCardActiveClass: string;
  effectCardTargetClass: string;
  buttonPrimaryClass: string;
  buttonSecondaryClass: string;
  buttonGhostClass: string;
  tagClass: string;
  mutedTextClass: string;
  headingTextClass: string;
  selectClass: string;
  inputClass: string;
  checkboxClass: string;
  dropzoneBaseClass: string;
  dropzoneActiveClass: string;
  dropzoneDisabledClass: string;
  audioPanelClass: string;
  audioPlayButtonClass: string;
  accentColor: string;
  waveColor: string;
  waveProgressColor: string;
  effectListClass?: string;
  effectCardWrapperClass?: string;
  effectCardBodyClass?: string;
  effectListEmptyClass?: string;
  mainInnerClass?: string;
  playerStackClass?: string;
  controlRowClass?: string;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "sunsetBloom",
    name: "Sunset Bloom",
    description: "Warm oranges and pinks with stacked sections and soft glass surfaces.",
    layout: "stacked",
    bodyClass: "bg-gradient-to-br from-rose-100 via-orange-100 to-amber-200 text-rose-900",
    headerClass: "bg-white/80 border-b border-amber-200 backdrop-blur",
    headerTitleClass: "text-rose-700",
    layoutWrapperClass: "flex flex-col gap-8",
    effectsWrapperClass: "order-2",
    mainWrapperClass: "order-1",
    effectPanelClass: "bg-white/90 border border-rose-200 shadow-lg shadow-rose-200/60 rounded-3xl backdrop-blur",
    mainPanelClass: "bg-white/90 border border-amber-200 shadow-xl shadow-amber-200/60 rounded-3xl backdrop-blur",
    effectCardClass: "bg-rose-50/90 border border-rose-200 rounded-2xl",
    effectCardActiveClass: "border-amber-400 shadow-[0_0_25px_rgba(245,158,11,0.35)]",
    effectCardTargetClass: "border-amber-300 bg-amber-100/60",
    buttonPrimaryClass: "bg-rose-500 hover:bg-rose-400 text-white rounded-full uppercase tracking-wide px-5 py-2",
    buttonSecondaryClass: "bg-amber-100 hover:bg-amber-200 text-amber-700 border border-amber-300 rounded-full uppercase tracking-wide px-5 py-2",
    buttonGhostClass: "bg-white hover:bg-rose-100 text-rose-600 border border-rose-200 rounded-full uppercase tracking-wide px-5 py-2",
    tagClass: "text-rose-600 bg-rose-100 border border-rose-200 rounded-full px-2",
    mutedTextClass: "text-rose-400",
    headingTextClass: "text-rose-700",
    selectClass: "bg-white border border-rose-200 text-rose-700 rounded-full focus:ring-1 focus:ring-rose-400 focus:border-rose-400",
    inputClass: "bg-white border border-rose-200 text-rose-700 rounded-full focus:ring-1 focus:ring-rose-400 focus:border-rose-400 placeholder-rose-300",
    checkboxClass: "text-rose-500 focus:ring-rose-300 border-rose-300 rounded-md",
    dropzoneBaseClass: "border-rose-300 border-dashed bg-rose-50 text-rose-600 hover:bg-rose-100 rounded-[3rem]",
    dropzoneActiveClass: "border-amber-400 bg-amber-100 scale-[1.02]",
    dropzoneDisabledClass: "opacity-50 cursor-not-allowed",
    audioPanelClass: "bg-white/90 border border-rose-200 shadow-lg rounded-3xl",
    audioPlayButtonClass: "bg-rose-500 hover:bg-rose-400 text-white rounded-full uppercase tracking-wide px-5 py-2",
    accentColor: "#f472b6",
    waveColor: "#fca5a5",
    waveProgressColor: "#fb7185",
    effectListClass: "space-y-4",
    effectListEmptyClass: "text-center py-8 text-sm text-rose-400 uppercase tracking-wide",
    mainInnerClass: "space-y-6",
    playerStackClass: "space-y-4",
    controlRowClass: "flex flex-col gap-2 sm:flex-row",
  },
  {
    id: "neonCircuit",
    name: "Neon Circuit",
    description: "High-contrast synth cockpit with a horizontal effect strip and squared controls.",
    layout: "stacked",
    bodyClass: "bg-[radial-gradient(circle_at_top,_#020617,_#0f172a_55%,_#020617)] text-cyan-100",
    headerClass: "bg-transparent border-b border-cyan-400/40 backdrop-blur",
    headerTitleClass: "text-cyan-300 tracking-[0.5em] uppercase drop-shadow-[0_0_16px_rgba(6,182,212,0.45)]",
    layoutWrapperClass: "flex flex-col gap-12",
    effectsWrapperClass: "order-1",
    mainWrapperClass: "order-2",
    effectPanelClass: "bg-slate-950/80 border border-cyan-500/50 rounded-2xl shadow-[0_55px_140px_rgba(6,182,212,0.35)] px-6 py-6",
    mainPanelClass: "bg-slate-950/70 border border-indigo-700/40 rounded-2xl shadow-[0_45px_140px_rgba(79,70,229,0.35)] px-7 py-7",
    effectCardClass: "bg-slate-900/85 border border-cyan-400/40 rounded-md h-full",
    effectCardActiveClass: "border-emerald-300 shadow-[0_0_28px_rgba(16,185,129,0.55)]",
    effectCardTargetClass: "border-cyan-200 bg-cyan-500/20",
    buttonPrimaryClass: "bg-cyan-300 hover:bg-cyan-200 text-slate-900 uppercase tracking-[0.45em] px-6 py-2.5 rounded-none border border-cyan-400",
    buttonSecondaryClass: "bg-slate-950 hover:bg-slate-900 text-slate-100 border border-slate-600 uppercase tracking-[0.35em] px-6 py-2.5 rounded-none",
    buttonGhostClass: "bg-transparent border border-cyan-300 text-cyan-100 hover:bg-cyan-500/10 uppercase tracking-[0.35em] px-6 py-2.5 rounded-none",
    tagClass: "text-cyan-200 bg-cyan-500/10 border border-cyan-400/30 px-3 py-1 uppercase tracking-[0.28em]",
    mutedTextClass: "text-slate-400 uppercase tracking-[0.3em]",
    headingTextClass: "text-cyan-200 uppercase tracking-[0.35em]",
    selectClass: "bg-slate-950 border border-cyan-400/40 text-cyan-100 rounded-none uppercase tracking-[0.3em] focus:ring-1 focus:ring-cyan-300 focus:border-cyan-300",
    inputClass: "bg-slate-950 border border-cyan-400/40 text-cyan-100 rounded-none uppercase tracking-[0.3em] focus:ring-1 focus:ring-cyan-300 focus:border-cyan-300 placeholder-slate-500",
    checkboxClass: "text-cyan-300 focus:ring-cyan-200 border-cyan-400 bg-slate-900 rounded-sm",
    dropzoneBaseClass: "border-cyan-400/40 border-dashed bg-slate-950 text-cyan-200 hover:bg-slate-900 uppercase tracking-[0.35em] px-9 py-10",
    dropzoneActiveClass: "border-emerald-300 bg-emerald-400/20 scale-[1.02]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-slate-900/80 border border-cyan-400/40 rounded-xl",
    audioPlayButtonClass: "bg-cyan-300 hover:bg-cyan-200 text-slate-900 uppercase tracking-[0.35em] px-6 py-2.5 rounded-none",
    accentColor: "#22d3ee",
    waveColor: "#1e1b4b",
    waveProgressColor: "#22d3ee",
    effectListClass: "flex gap-5 overflow-x-auto pb-5 snap-x snap-mandatory",
    effectCardWrapperClass: "min-w-[260px] snap-center",
    effectCardBodyClass: "h-full",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.35em] text-cyan-200",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-5",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-4",
  },
  {
    id: "concreteSuite",
    name: "Concrete Suite",
    description: "Brutalist mastering room with tall concrete slabs and precise sans-serif controls.",
    layout: "split-left",
    bodyClass: "bg-[radial-gradient(circle_at_top_left,_#121212,_#1f1f1f_60%,_#050505)] text-zinc-200",
    headerClass: "bg-zinc-950/90 border-b border-zinc-700 backdrop-blur",
    headerTitleClass: "text-zinc-100 uppercase tracking-[0.5em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-14",
    effectsWrapperClass: "xl:w-[30rem] order-1 sticky top-28 self-start",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-zinc-950/85 border border-zinc-700 shadow-[0_45px_160px_rgba(0,0,0,0.65)] rounded-[2.2rem] px-8 py-9 max-h-[calc(100vh-14rem)] overflow-y-auto",
    mainPanelClass: "bg-zinc-950/80 border border-zinc-700 shadow-[0_55px_180px_rgba(0,0,0,0.6)] rounded-[2.5rem] px-8 py-10",
    effectCardClass: "bg-zinc-900 border border-zinc-600 rounded-none",
    effectCardActiveClass: "border-white shadow-[0_0_32px_rgba(255,255,255,0.35)]",
    effectCardTargetClass: "border-zinc-300 bg-zinc-800",
    buttonPrimaryClass: "bg-white hover:bg-zinc-200 text-black rounded-none uppercase tracking-[0.5em] px-6 py-3 border border-white",
    buttonSecondaryClass: "bg-zinc-900 hover:bg-zinc-800 text-white border border-zinc-700 rounded-none uppercase tracking-[0.4em] px-6 py-3",
    buttonGhostClass: "bg-transparent border border-zinc-600 text-white hover:bg-zinc-800 rounded-none uppercase tracking-[0.4em] px-6 py-3",
    tagClass: "text-black bg-white uppercase tracking-[0.45em] px-2 rounded-none",
    mutedTextClass: "text-zinc-400 uppercase tracking-[0.35em]",
    headingTextClass: "text-white uppercase tracking-[0.45em]",
    selectClass: "bg-black border border-zinc-700 text-white rounded-none uppercase text-xs focus:ring-1 focus:ring-white focus:border-white",
    inputClass: "bg-black border border-zinc-700 text-white rounded-none uppercase text-xs focus:ring-1 focus:ring-white focus:border-white placeholder-zinc-500",
    checkboxClass: "text-white focus:ring-white border-zinc-700 bg-black rounded-none",
    dropzoneBaseClass: "border-zinc-700 border-dashed bg-black text-white hover:bg-zinc-900 rounded-none uppercase tracking-[0.35em] px-9 py-12",
    dropzoneActiveClass: "border-white bg-zinc-800 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-black border border-zinc-700 rounded-[2.4rem] shadow-lg",
    audioPlayButtonClass: "bg-white hover:bg-zinc-200 text-black rounded-none uppercase tracking-[0.4em] px-6 py-3",
    accentColor: "#ffffff",
    waveColor: "#525252",
    waveProgressColor: "#ffffff",
    effectListClass: "space-y-5 pr-2",
    effectListEmptyClass: "text-center py-14 text-sm uppercase tracking-[0.4em] text-zinc-500",
    mainInnerClass: "space-y-12",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-4",
  },
  {
    id: "studioOak",
    name: "Studio Oak",
    description: "Warm studio desk with a vertical band of controls beside a wide instrument stage.",
    layout: "split-left",
    bodyClass: "bg-[linear-gradient(120deg,_#3a2a1a,_#262118_55%,_#1c1917)] text-amber-100",
    headerClass: "bg-stone-950/80 border-b border-amber-700/40 backdrop-blur",
    headerTitleClass: "text-amber-200 uppercase tracking-[0.35em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-12",
    effectsWrapperClass: "xl:w-[24rem] order-1 sticky top-28 self-start",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-gradient-to-b from-stone-900/90 to-stone-950/95 border border-amber-700/50 rounded-[3rem] px-7 py-8 shadow-[0_45px_140px_rgba(88,64,43,0.4)] max-h-[calc(100vh-12rem)] overflow-y-auto",
    mainPanelClass: "bg-stone-950/80 border border-amber-700/45 rounded-[3rem] px-9 py-10 shadow-[0_55px_160px_rgba(68,32,10,0.4)]",
    effectCardClass: "bg-stone-900/80 border border-amber-600/45 rounded-[1.5rem]",
    effectCardActiveClass: "border-amber-300 shadow-[0_0_34px_rgba(251,191,36,0.45)]",
    effectCardTargetClass: "border-amber-200 bg-amber-500/25",
    buttonPrimaryClass: "bg-amber-400 hover:bg-amber-300 text-stone-950 rounded-sm uppercase tracking-[0.38em] px-6 py-3 border border-amber-200",
    buttonSecondaryClass: "bg-stone-900/70 hover:bg-stone-800 text-amber-100 border border-stone-700 rounded-sm uppercase tracking-[0.32em] px-6 py-3",
    buttonGhostClass: "bg-transparent border border-amber-400 text-amber-200 hover:bg-amber-500/15 rounded-sm uppercase tracking-[0.32em] px-6 py-3",
    tagClass: "text-amber-200 bg-amber-500/15 border border-amber-400/40 rounded-full px-3 uppercase tracking-wide",
    mutedTextClass: "text-amber-200/70 uppercase tracking-[0.3em]",
    headingTextClass: "text-amber-100 uppercase tracking-[0.35em]",
    selectClass: "bg-stone-950 border border-amber-600/45 text-amber-100 rounded-sm uppercase tracking-[0.3em] focus:ring-1 focus:ring-amber-300 focus:border-amber-300",
    inputClass: "bg-stone-950 border border-amber-600/45 text-amber-100 rounded-sm uppercase tracking-[0.3em] focus:ring-1 focus:ring-amber-300 focus:border-amber-300 placeholder-amber-300",
    checkboxClass: "text-amber-300 focus:ring-amber-200 border-amber-600/60 bg-stone-900 rounded",
    dropzoneBaseClass: "border-amber-500/35 border-dashed bg-stone-950 text-amber-200 hover:bg-stone-900 rounded-[2.5rem] uppercase tracking-[0.35em] px-9 py-11",
    dropzoneActiveClass: "border-amber-200 bg-amber-400/20 scale-[1.02]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-stone-900/80 border border-amber-600/45 rounded-[2.5rem] shadow-lg",
    audioPlayButtonClass: "bg-amber-400 hover:bg-amber-300 text-stone-950 rounded-sm uppercase tracking-[0.32em] px-6 py-3",
    accentColor: "#fcd34d",
    waveColor: "#b45309",
    waveProgressColor: "#fbbf24",
    effectListClass: "space-y-5 pr-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.32em] text-amber-300",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-4",
  },
  {
    id: "waveCanvas",
    name: "Wave Canvas",
    description: "Spatial canvas with twin wave decks and effect cards sliding along a left rail.",
    layout: "theater",
    bodyClass: "bg-gradient-to-b from-[#0f172a] via-[#1e3a8a] to-[#0f172a] text-sky-100",
    headerClass: "bg-transparent border-b border-sky-500/40 backdrop-blur",
    headerTitleClass: "text-sky-200 uppercase tracking-[0.4em] drop-shadow-[0_0_16px_rgba(125,211,252,0.5)]",
    layoutWrapperClass: "flex flex-col gap-12",
    effectsWrapperClass: "order-1",
    mainWrapperClass: "order-2",
    effectPanelClass: "bg-sky-950/70 border border-sky-500/40 rounded-[2rem] px-6 py-6 shadow-[0_35px_140px_rgba(14,165,233,0.3)]",
    mainPanelClass: "bg-sky-950/60 border border-sky-500/40 rounded-[2.5rem] px-8 py-8 shadow-[0_55px_160px_rgba(59,130,246,0.3)]",
    effectCardClass: "bg-sky-900/70 border border-sky-500/40 rounded-lg",
    effectCardActiveClass: "border-cyan-300 shadow-[0_0_30px_rgba(34,211,238,0.5)]",
    effectCardTargetClass: "border-emerald-300 bg-emerald-500/20",
    buttonPrimaryClass: "bg-sky-400 hover:bg-sky-300 text-sky-950 rounded-lg uppercase tracking-[0.35em] px-6 py-3",
    buttonSecondaryClass: "bg-sky-900/70 hover:bg-sky-800 text-sky-100 border border-sky-500/50 rounded-lg uppercase tracking-[0.3em] px-6 py-3",
    buttonGhostClass: "bg-transparent border border-sky-300 text-sky-200 hover:bg-sky-500/10 rounded-lg uppercase tracking-[0.3em] px-6 py-3",
    tagClass: "text-sky-200 bg-sky-500/15 border border-sky-400/35 rounded-full px-3 uppercase tracking-wide",
    mutedTextClass: "text-sky-200/75 uppercase tracking-[0.25em]",
    headingTextClass: "text-sky-100 uppercase tracking-[0.35em]",
    selectClass: "bg-sky-950/70 border border-sky-500/40 text-sky-100 rounded-lg uppercase tracking-[0.3em] focus:ring-1 focus:ring-sky-300 focus:border-sky-300",
    inputClass: "bg-sky-950/70 border border-sky-500/40 text-sky-100 rounded-lg uppercase tracking-[0.3em] focus:ring-1 focus:ring-sky-300 focus:border-sky-300 placeholder-sky-300/60",
    checkboxClass: "text-sky-300 focus:ring-sky-200 border-sky-500/60 bg-sky-900 rounded",
    dropzoneBaseClass: "border-sky-400/40 border-dashed bg-sky-950/70 text-sky-200 hover:bg-sky-900/60 rounded-[3rem] uppercase tracking-[0.35em] px-9 py-11",
    dropzoneActiveClass: "border-cyan-300 bg-cyan-400/20 scale-[1.02]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-sky-900/70 border border-sky-500/40 rounded-[2.5rem] shadow-lg",
    audioPlayButtonClass: "bg-sky-400 hover:bg-sky-300 text-sky-950 rounded-lg uppercase tracking-[0.35em] px-6 py-3",
    accentColor: "#38bdf8",
    waveColor: "#1d4ed8",
    waveProgressColor: "#38bdf8",
    effectListClass: "flex flex-col gap-4",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.35em] text-sky-300",
    mainInnerClass: "space-y-8",
    playerStackClass: "grid gap-6 md:grid-cols-2",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-4",
  },
  {
    id: "icePanel",
    name: "Ice Panel",
    description: "Crisp clinical interface with pill controls in an airy floating sidebar.",
    layout: "split-left",
    bodyClass: "bg-gradient-to-tr from-slate-100 via-sky-100 to-white text-slate-800",
    headerClass: "bg-white/80 border-b border-sky-200 backdrop-blur",
    headerTitleClass: "text-sky-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[19rem] order-1 sticky top-28 self-start",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white/85 border border-sky-200 rounded-[3rem] shadow-[0_35px_120px_rgba(14,165,233,0.2)] backdrop-blur-xl px-7 py-8",
    mainPanelClass: "bg-white/78 border border-slate-200 rounded-[3rem] shadow-[0_45px_140px_rgba(15,23,42,0.15)] backdrop-blur-xl px-8 py-9",
    effectCardClass: "bg-white border border-sky-200 rounded-full",
    effectCardActiveClass: "border-sky-400 shadow-[0_0_30px_rgba(125,211,252,0.45)]",
    effectCardTargetClass: "border-emerald-300 bg-emerald-200/40",
    buttonPrimaryClass: "bg-sky-500 hover:bg-sky-400 text-white rounded-full uppercase tracking-[0.35em] px-6 py-3",
    buttonSecondaryClass: "bg-white hover:bg-sky-100 text-sky-600 border border-sky-300 rounded-full uppercase tracking-[0.3em] px-6 py-3",
    buttonGhostClass: "bg-transparent border border-sky-300 text-sky-600 hover:bg-sky-100/70 rounded-full uppercase tracking-[0.3em] px-6 py-3",
    tagClass: "text-sky-600 bg-sky-100 border border-sky-200 rounded-full px-3 uppercase tracking-wide",
    mutedTextClass: "text-slate-400 uppercase tracking-[0.25em]",
    headingTextClass: "text-sky-700 uppercase tracking-[0.35em]",
    selectClass: "bg-white border border-sky-200 text-slate-700 rounded-full uppercase tracking-[0.28em] focus:ring-1 focus:ring-sky-400 focus:border-sky-400",
    inputClass: "bg-white border border-sky-200 text-slate-700 rounded-full uppercase tracking-[0.28em] focus:ring-1 focus:ring-sky-400 focus:border-sky-400 placeholder-sky-200",
    checkboxClass: "text-sky-500 focus:ring-sky-300 border-sky-300 rounded",
    dropzoneBaseClass: "border-sky-300 border-dashed bg-white text-sky-600 hover:bg-sky-100 rounded-[3.5rem] uppercase tracking-[0.32em] px-9 py-11",
    dropzoneActiveClass: "border-emerald-300 bg-emerald-200/40 scale-[1.02]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white/85 border border-sky-200 rounded-[3rem] shadow-lg",
    audioPlayButtonClass: "bg-sky-500 hover:bg-sky-400 text-white rounded-full uppercase tracking-[0.32em] px-6 py-3",
    accentColor: "#0ea5e9",
    waveColor: "#bae6fd",
    waveProgressColor: "#0ea5e9",
    effectListClass: "space-y-4",
    effectListEmptyClass: "text-center py-10 text-sm uppercase tracking-[0.3em] text-sky-400",
    mainInnerClass: "space-y-6",
    playerStackClass: "space-y-4",
    controlRowClass: "flex flex-col gap-3 sm:flex-row",
  },
  {
    id: "gridliner",
    name: "Gridliner",
    description: "Blueprint drafting room with a sticky matrix of tiles and technical outlines.",
    layout: "grid",
    bodyClass: "bg-[linear-gradient(135deg,_#0f172a,_#1d4ed8_55%,_#0f172a)] text-sky-100",
    headerClass: "bg-blue-950/80 border-b border-sky-400/40 backdrop-blur",
    headerTitleClass: "text-sky-200 tracking-[0.45em] uppercase",
    layoutWrapperClass: "grid gap-10 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,1.7fr)]",
    effectsWrapperClass: "order-1 sticky top-28 self-start",
    mainWrapperClass: "order-2",
    effectPanelClass: "bg-blue-950/85 border border-sky-500/40 rounded-[3rem] shadow-[0_50px_160px_rgba(30,64,175,0.35)] max-h-[calc(100vh-12rem)] overflow-y-auto px-8 py-9",
    mainPanelClass: "bg-blue-950/70 border border-sky-500/40 rounded-[3rem] shadow-[0_60px_180px_rgba(30,64,175,0.35)] px-9 py-9",
    effectCardClass: "bg-blue-950 border border-sky-500/40 rounded-xl",
    effectCardActiveClass: "border-sky-300 shadow-[0_0_40px_rgba(125,211,252,0.55)]",
    effectCardTargetClass: "border-emerald-300 bg-emerald-400/20",
    buttonPrimaryClass: "bg-sky-400 hover:bg-sky-300 text-blue-950 rounded-none uppercase tracking-[0.45em] px-6 py-3",
    buttonSecondaryClass: "bg-blue-900/80 hover:bg-blue-800 text-sky-200 border border-sky-400/40 rounded-none uppercase tracking-[0.4em] px-6 py-3",
    buttonGhostClass: "bg-transparent border border-sky-300/60 text-sky-200 hover:bg-sky-400/10 rounded-none uppercase tracking-[0.4em] px-6 py-3",
    tagClass: "text-blue-950 bg-sky-300 uppercase tracking-[0.4em] px-2 rounded-none",
    mutedTextClass: "text-sky-200/70 uppercase tracking-[0.38em]",
    headingTextClass: "text-sky-100 uppercase tracking-[0.45em]",
    selectClass: "bg-blue-950 border border-sky-500/40 text-sky-100 rounded-none uppercase text-xs focus:ring-1 focus:ring-sky-300 focus:border-sky-300",
    inputClass: "bg-blue-950 border border-sky-500/40 text-sky-100 rounded-none uppercase text-xs focus:ring-1 focus:ring-sky-300 focus:border-sky-300 placeholder-sky-300/50",
    checkboxClass: "text-sky-300 focus:ring-sky-300 border-sky-500 bg-blue-950 rounded-sm",
    dropzoneBaseClass: "border-sky-500/40 border-dashed bg-blue-950/80 text-sky-200 hover:bg-blue-900/70 rounded-none uppercase tracking-[0.45em] px-9 py-12",
    dropzoneActiveClass: "border-sky-300 bg-sky-400/10 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-blue-950/80 border border-sky-500/40 rounded-[2.5rem] shadow-lg",
    audioPlayButtonClass: "bg-sky-400 hover:bg-sky-300 text-blue-950 rounded-none uppercase tracking-[0.4em] px-6 py-3",
    accentColor: "#38bdf8",
    waveColor: "#1d4ed8",
    waveProgressColor: "#38bdf8",
    effectListClass: "grid gap-5 sm:grid-cols-2 xl:grid-cols-1",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.4em] text-sky-300",
    mainInnerClass: "space-y-10",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-4",
  },
  {
    id: "monoDesk",
    name: "Mono Desk",
    description: "Ultra-minimal white workstation with slim outlined controls and left-aligned cards.",
    layout: "split-left",
    bodyClass: "bg-[#f5f7fa] text-slate-900",
    headerClass: "bg-white border-b border-slate-200",
    headerTitleClass: "text-slate-700 uppercase tracking-[0.3em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-10",
    effectsWrapperClass: "xl:w-[20rem] order-1",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-white border border-slate-200 rounded-none shadow-[0_25px_50px_rgba(15,23,42,0.08)] px-6 py-8",
    mainPanelClass: "bg-white border border-slate-200 rounded-none shadow-[0_30px_60px_rgba(15,23,42,0.08)] px-8 py-10",
    effectCardClass: "bg-white border border-slate-200 rounded-none",
    effectCardActiveClass: "border-slate-900 shadow-[0_0_25px_rgba(15,23,42,0.2)]",
    effectCardTargetClass: "border-blue-400 bg-blue-100/60",
    buttonPrimaryClass: "bg-slate-900 hover:bg-slate-700 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    buttonSecondaryClass: "bg-white hover:bg-slate-100 text-slate-700 border border-slate-300 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    buttonGhostClass: "bg-transparent border border-slate-300 text-slate-600 hover:bg-slate-100 uppercase tracking-[0.25em] px-5 py-2 rounded-none",
    tagClass: "text-slate-600 bg-slate-100 border border-slate-200 uppercase tracking-wide px-2",
    mutedTextClass: "text-slate-500 uppercase tracking-[0.2em]",
    headingTextClass: "text-slate-700 uppercase tracking-[0.25em]",
    selectClass: "bg-white border border-slate-300 text-slate-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-slate-400 focus:border-slate-400",
    inputClass: "bg-white border border-slate-300 text-slate-700 rounded-none uppercase tracking-[0.2em] focus:ring-1 focus:ring-slate-400 focus:border-slate-400 placeholder-slate-400",
    checkboxClass: "text-slate-700 focus:ring-slate-400 border-slate-300 rounded-none",
    dropzoneBaseClass: "border-slate-300 border-dashed bg-white text-slate-600 hover:bg-slate-100 rounded-none uppercase tracking-[0.3em] px-8 py-10",
    dropzoneActiveClass: "border-blue-300 bg-blue-100/60 scale-[1.01]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-white border border-slate-200 rounded-none shadow-lg",
    audioPlayButtonClass: "bg-slate-900 hover:bg-slate-700 text-white uppercase tracking-[0.3em] px-5 py-2 rounded-none",
    accentColor: "#0f172a",
    waveColor: "#cbd5f5",
    waveProgressColor: "#0f172a",
    effectListClass: "space-y-3",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.3em] text-slate-400",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-6",
    controlRowClass: "grid grid-cols-1 sm:grid-cols-3 gap-3",
  },
  {
    id: "terminalGrid",
    name: "Terminal Grid",
    description: "Retro data terminal with green phosphor effect tiles stacked in a roaring console.",
    layout: "split-left",
    bodyClass: "bg-black text-emerald-300",
    headerClass: "bg-black/95 border-b border-emerald-500/40",
    headerTitleClass: "text-emerald-400 font-mono uppercase tracking-[0.5em]",
    layoutWrapperClass: "flex flex-col xl:flex-row gap-12",
    effectsWrapperClass: "xl:w-[22rem] order-1 sticky top-32 self-start",
    mainWrapperClass: "flex-1 order-2",
    effectPanelClass: "bg-black border border-emerald-500/40 rounded-lg px-6 py-8 shadow-[0_50px_140px_rgba(16,185,129,0.35)]",
    mainPanelClass: "bg-black border border-emerald-500/40 rounded-lg px-8 py-9 shadow-[0_45px_160px_rgba(16,185,129,0.35)]",
    effectCardClass: "bg-black border border-emerald-500/40 font-mono",
    effectCardActiveClass: "border-emerald-300 shadow-[0_0_30px_rgba(34,197,94,0.55)]",
    effectCardTargetClass: "border-emerald-200 bg-emerald-500/15",
    buttonPrimaryClass: "bg-emerald-400 hover:bg-emerald-300 text-black font-mono uppercase tracking-[0.45em] px-5 py-2",
    buttonSecondaryClass: "bg-black border border-emerald-400 text-emerald-300 hover:bg-emerald-500/10 font-mono uppercase tracking-[0.35em] px-5 py-2",
    buttonGhostClass: "bg-transparent border border-emerald-400 text-emerald-300 hover:bg-emerald-500/10 font-mono uppercase tracking-[0.35em] px-5 py-2",
    tagClass: "text-black bg-emerald-400 uppercase tracking-[0.45em] px-2 font-mono",
    mutedTextClass: "text-emerald-200/70 font-mono uppercase tracking-[0.3em]",
    headingTextClass: "text-emerald-200 font-mono uppercase tracking-[0.4em]",
    selectClass: "bg-black border border-emerald-500 text-emerald-300 font-mono uppercase text-xs focus:ring-1 focus:ring-emerald-300 focus:border-emerald-300",
    inputClass: "bg-black border border-emerald-500 text-emerald-300 font-mono uppercase text-xs focus:ring-1 focus:ring-emerald-300 focus:border-emerald-300 placeholder-emerald-300/60",
    checkboxClass: "text-emerald-400 focus:ring-emerald-300 border-emerald-500 bg-black",
    dropzoneBaseClass: "border-emerald-500 border-dashed bg-black text-emerald-300 hover:bg-emerald-500/15 font-mono uppercase tracking-[0.4em] px-9 py-11",
    dropzoneActiveClass: "border-emerald-200 bg-emerald-500/25 scale-[1.02]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-black border border-emerald-500/40 font-mono",
    audioPlayButtonClass: "bg-emerald-400 hover:bg-emerald-300 text-black font-mono uppercase tracking-[0.4em] px-5 py-2",
    accentColor: "#34d399",
    waveColor: "#064e3b",
    waveProgressColor: "#34d399",
    effectListClass: "space-y-4",
    effectListEmptyClass: "text-center py-12 text-sm font-mono uppercase tracking-[0.35em] text-emerald-300",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-5",
    controlRowClass: "flex flex-col gap-3",
  },
  {
    id: "auroraStage",
    name: "Aurora Stage",
    description: "Immersive stage lighting with major focus on the decks and a low effect timeline dock.",
    layout: "stacked-reverse",
    bodyClass: "bg-[radial-gradient(circle_at_center,_#0f172a,_#1e1b4b_65%,_#111827)] text-indigo-100",
    headerClass: "bg-transparent border-b border-indigo-800/50 backdrop-blur",
    headerTitleClass: "text-indigo-200 tracking-[0.45em] uppercase drop-shadow-[0_0_20px_rgba(129,140,248,0.65)]",
    layoutWrapperClass: "flex flex-col gap-12",
    effectsWrapperClass: "order-2",
    mainWrapperClass: "order-1",
    effectPanelClass: "bg-indigo-950/70 border border-indigo-700/40 rounded-[2.5rem] shadow-[0_-35px_140px_rgba(99,102,241,0.35)] backdrop-blur-xl px-6 py-7",
    mainPanelClass: "bg-indigo-950/60 border border-indigo-700/40 rounded-[2.8rem] shadow-[0_55px_160px_rgba(79,70,229,0.35)] backdrop-blur-xl px-9 py-9",
    effectCardClass: "bg-indigo-900/70 border border-indigo-600/40 rounded-xl",
    effectCardActiveClass: "border-indigo-300 shadow-[0_0_38px_rgba(129,140,248,0.55)]",
    effectCardTargetClass: "border-cyan-300 bg-cyan-500/25",
    buttonPrimaryClass: "bg-indigo-500 hover:bg-indigo-400 text-white rounded-full uppercase tracking-[0.35em] px-6 py-3",
    buttonSecondaryClass: "bg-indigo-900/70 hover:bg-indigo-800 text-indigo-100 border border-indigo-500/50 rounded-full uppercase tracking-[0.32em] px-6 py-3",
    buttonGhostClass: "bg-transparent border border-indigo-400/60 text-indigo-200 hover:bg-indigo-500/10 rounded-full uppercase tracking-[0.3em] px-6 py-3",
    tagClass: "text-indigo-200 bg-indigo-500/10 border border-indigo-400/40 rounded-full px-3 uppercase tracking-wide",
    mutedTextClass: "text-indigo-200/70 uppercase tracking-[0.25em]",
    headingTextClass: "text-indigo-100 uppercase tracking-[0.35em]",
    selectClass: "bg-indigo-950/70 border border-indigo-600/50 text-indigo-100 rounded-full uppercase tracking-[0.3em] focus:ring-1 focus:ring-indigo-300 focus:border-indigo-300",
    inputClass: "bg-indigo-950/70 border border-indigo-600/50 text-indigo-100 rounded-full uppercase tracking-[0.3em] focus:ring-1 focus:ring-indigo-300 focus:border-indigo-300 placeholder-indigo-300/60",
    checkboxClass: "text-indigo-400 focus:ring-indigo-200 border-indigo-600/60 bg-indigo-900 rounded",
    dropzoneBaseClass: "border-indigo-500/40 border-dashed bg-indigo-950/70 text-indigo-200 hover:bg-indigo-900/60 rounded-[3.5rem] uppercase tracking-[0.35em] px-9 py-11",
    dropzoneActiveClass: "border-cyan-300 bg-cyan-400/20 scale-[1.02]",
    dropzoneDisabledClass: "opacity-40 cursor-not-allowed",
    audioPanelClass: "bg-indigo-900/70 border border-indigo-600/50 rounded-[2.5rem] shadow-lg",
    audioPlayButtonClass: "bg-indigo-500 hover:bg-indigo-400 text-white rounded-full uppercase tracking-[0.35em] px-6 py-3",
    accentColor: "#818cf8",
    waveColor: "#312e81",
    waveProgressColor: "#818cf8",
    effectListClass: "flex gap-5 overflow-x-auto pb-6 snap-x snap-mandatory",
    effectCardWrapperClass: "min-w-[260px] snap-center",
    effectCardBodyClass: "h-full",
    effectListEmptyClass: "text-center py-12 text-sm uppercase tracking-[0.35em] text-indigo-300",
    mainInnerClass: "space-y-8",
    playerStackClass: "space-y-5",
    controlRowClass: "flex flex-col gap-4 sm:flex-row sm:items-center",
  }
];
